language: cpp
dist: trusty
sudo: false
git:
  depth: 99999  # our build requires a full clone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libboost-all-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-net-dev
      - libsdl2-mixer-dev
      - libglew-dev
before_install:
  - wget 'https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz'
  - tar -xf cmake-3.8.2-Linux-x86_64.tar.gz
  - export PATH=$(pwd)/cmake-3.8.2-Linux-x86_64/bin:$PATH
  - export CC=gcc-7 CXX=g++-7
script: mkdir build && cd build && cmake .. && make -j 2 && ./rwe_test
